[package]
name = "bz2-fastdl"
version = "1.0.0"
authors = ["CirnoV <cirnov59@gmail.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bzip2 = "0.5"
rayon = "1.10"
clap = { version = "4.5", features = ["derive"] }
walkdir = "2"
anyhow = "1"
